fact_kind(agent_,[term,term]).
fact_kind(agricultural_service,[term,term,term]).
fact_kind(alice_employer,[term,term,term]).
fact_kind(alice_household_maintenance,[term,term,term,term]).
fact_kind(american_employer_,[term]).
fact_kind(amount_,[term,int]).
fact_kind(attending_classes_,[term]).
fact_kind(beneficiary_,[term,term]).
fact_kind(birth_,[term]).
fact_kind(blindness_,[term]).
fact_kind(brother_,[term]).
fact_kind(business_,[term]).
fact_kind(business_trust_,[term]).
fact_kind(citizenship_,[term]).
fact_kind(country_,[term,term]).
fact_kind(daughter_,[term]).
fact_kind(death_,[term]).
fact_kind(deduction_,[term]).
fact_kind(destination_,[term,term]).
fact_kind(disability_,[term]).
fact_kind(educational_institution_,[term]).
fact_kind(end_,[term,day]).
fact_kind(enrollment_,[term]).
fact_kind(father_,[term]).
fact_kind(hospital_,[term]).
fact_kind(incarceration_,[term]).
fact_kind(income_,[term]).
fact_kind(international_organization_,[term]).
fact_kind(itemize_deductions_,[term]).
fact_kind(joint_return_,[term]).
fact_kind(legal_separation_,[term]).
fact_kind(location_,[term,term]).
fact_kind(marriage_,[term]).
fact_kind(means_,[term,term]).
fact_kind(medical_institution_,[term]).
fact_kind(medical_patient_,[term]).
fact_kind(migration_,[term]).
fact_kind(mother_,[term]).
fact_kind(nonresident_alien_,[term]).
fact_kind(nurses_training_school_,[term]).
fact_kind(patient,[term,term]).
fact_kind(patient_,[term,term]).
fact_kind(payment_,[term]).
fact_kind(penal_institution_,[term]).
fact_kind(plan_,[term]).
fact_kind(purpose_,[pat,term]).
fact_kind(reason_,[term,term]).
fact_kind(residence_,[term]).
fact_kind(retirement_,[term]).
fact_kind(service_,[term]).
fact_kind(sibling_,[term]).
fact_kind(sister_,[term]).
fact_kind(son_,[term]).
fact_kind(start_,[term,day]).
fact_kind(termination_,[term]).
fact_kind(type_,[term,term]).
fact_kind(unemployment_compensation_agreement_,[term]).
stip_kind(s63,3,s63_3).
stip_kind(s7703,4,s7703_4).
stip_kind(s3306_b,8,s3306_b_8).
stip_kind(s2_b,3,s2_b_3).
stip_kind(s2_a,3,s2_a_3).
stip_kind(s151_c_applies,3,s151_c_applies_3).
stip_kind(s152_c_1,3,s152_c_1_3).
stip_kind(s3306_c,5,s3306_c_5).
stip_kind(s151,5,s151_5).
stip_kind(s151_d,4,s151_d_4).
stip_kind(s151_b_applies,3,s151_b_applies_3).
stip_kind(s151_c,4,s151_c_4).
stip_kind(s151_b_applies,2,s151_b_applies_2).
stip_kind(total_wages_employer,6,total_wages_employer_6).
stip_kind(s68_b,3,s68_b_3).
stip_kind(s152_c_2,4,s152_c_2_4).
stip_kind(s152_c,3,s152_c_3).
stip_kind(s152_b_2,4,s152_b_2_4).
stip_kind(s3306_a,2,s3306_a_2).
stip_kind(s63_c_1,3,s63_c_1_3).
stip_kind(s63_c_2,3,s63_c_2_3).
stip_kind(s63_c_3,3,s63_c_3_3).
stip_kind(s63_f_1_A,2,s63_f_1_A_2).
stip_kind(s63_f_1_B,3,s63_f_1_B_3).
stip_kind(s63_d,4,s63_d_4).
stip_kind(s152_c_3,3,s152_c_3_3).
stip_kind(s2_a,5,s2_a_5).
stip_kind(s152_d_2_H,6,s152_d_2_H_6).
stip_kind(s63_c,3,s63_c_3).
stip_kind(s63_c_3,4,s63_c_3_4).
stip_kind(s151_b,3,s151_b_3).
