#!/usr/bin/env python3
"""Check shared time-role tables, without reading either producer or the meter.

--render-query prints the generated Lean registry; --render-stip prints the
marked Household section. Normal invocation verifies both checked-in products.
Regeneration is a mechanical copy of the reviewed TIME_SCHEMA.json declaration,
not inference from variable names or from either lane's implementation.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
BEGIN = "-- BEGIN GENERATED STIPULATION TIME ROLES"
END = "-- END GENERATED STIPULATION TIME ROLES"


def tables():
    data = json.loads((ROOT / "Interface/TIME_SCHEMA.json").read_text())
    assert data["schema_version"] == 1
    rows = data["signatures"]
    seen = set()
    for row in rows:
        key = (row["predicate"], row["arity"])
        assert key not in seen, f"duplicate signature: {key}"
        seen.add(key)
        assert re.fullmatch(r"[a-z][A-Za-z0-9_]*", key[0]), key
        assert len(row["roles"]) == key[1], key
        assert all(r in {"term", "day", "days", "year", "yearText"} for r in row["roles"]), key
        assert row["authority"] and row["source"], key
        assert all(len(m) == key[1] and set(m) <= {"b", "f"} for m in row["modes"]), key
    assert sum(r["stipulation"] for r in rows) == 31
    assert sum(r["queried"] for r in rows) == 135
    # Completeness against the owner tables is lexical: no semantic inference.
    decisions = (ROOT / "human/DECISIONS.md").read_text()
    queried = set(re.findall(r"\| §[^|]+\| `([a-z][A-Za-z0-9_]*)/(\d+)`", decisions))
    actual = {(r["predicate"], str(r["arity"])) for r in rows if r["queried"]}
    assert queried == actual, f"H6.5 mismatch: missing={queried-actual}, extra={actual-queried}"
    return rows


def roles(row):
    return "[" + ", ".join("." + r for r in row["roles"]) + "]"


def render_query(rows):
    lines = ["import Interface.Household", "", "/-! Generated by scripts/check_time_schema.py --render-query from",
             "Interface/TIME_SCHEMA.json. A shared signature declaration, not lane code.",
             "Time roles alone do not establish target modes or non-time kind constraints. -/",
             "", "namespace KMLA", "", "def queryTimeSchema? (predicate : String) (arity : Nat) : Option (List TimeRole) :=",
             "  match predicate, arity with"]
    for row in rows:
        lines.append(f'  | "{row["predicate"]}", {row["arity"]} => some {roles(row)}')
    lines += ["  | _, _ => none", "", "end KMLA", ""]
    return "\n".join(lines)


def render_stip(rows):
    # Keep the order of the existing H4.1 constructors, not lexicographic order.
    source = (ROOT / "Interface/Household.lean").read_text()
    constructors = re.findall(r"  \| ([a-z][A-Za-z0-9_]*)\n", source.split("inductive StipPred where", 1)[1].split("  deriving", 1)[0])
    by_constructor = {f'{r["predicate"]}_{r["arity"]}': r for r in rows if r["stipulation"]}
    assert set(constructors) == set(by_constructor), "H4.1 constructor population changed"
    lines = [BEGIN,
             "-- Generated from Interface/TIME_SCHEMA.json; scripts/check_time_schema.py",
             "-- verifies this table without loading either implementation lane.",
             "def StipPred.timeRoles : StipPred → List TimeRole"]
    lines += [f"  | .{name} => {roles(by_constructor[name])}" for name in constructors]
    lines.append(END)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--render-query", action="store_true")
    parser.add_argument("--render-stip", action="store_true")
    args = parser.parse_args()
    try:
        rows = tables()
        if args.render_query:
            print(render_query(rows), end="")
        elif args.render_stip:
            print(render_stip(rows))
        else:
            query = (ROOT / "Interface/QuerySchema.lean").read_text()
            assert query == render_query(rows), "QuerySchema.lean drift"
            hh = (ROOT / "Interface/Household.lean").read_text()
            actual = BEGIN + hh.split(BEGIN, 1)[1].split(END, 1)[0] + END
            assert actual == render_stip(rows), "StipPred.timeRoles drift"
            print(f"ok: {len(rows)} shared signatures; 135 queried; 31 stipulated; generated tables match")
    except (AssertionError, KeyError, ValueError, OSError) as error:
        print(f"time schema: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
