#!/usr/bin/env python3
"""Mechanical Q-024 evidence: each case's first test goal, its mode and its % Question.

Reads only human/sara/sara/cases/*.pl, human/DECISIONS.md (the H6.5 table) and
Interface/TIME_SCHEMA.json, all read-only. It decides nothing: it records which
positions each case binds and what the case's question says, and checks the
parsed modes against H6.5. Run from the repository root:

    python3 -I -B docs/consult/evidence/q024-question-bindings/extract.py
"""
import collections
import json
from pathlib import Path
import re
import sys

ROOT = Path.cwd()
OUT = ROOT / "docs/consult/evidence/q024-question-bindings/BINDINGS.md"


def split_args(text):
    """Split a Prolog argument list at top-level commas."""
    args, depth, quote, start = [], 0, None, 0
    for i, ch in enumerate(text):
        if quote:
            if ch == quote and text[i - 1] != "\\":
                quote = None
        elif ch in "'\"":
            quote = ch
        elif ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == "," and depth == 0:
            args.append(text[start:i].strip())
            start = i + 1
    args.append(text[start:].strip())
    return args


def first_call(goal):
    """(negated, predicate, args, rest) for the first call of a directive body."""
    body = goal.strip()
    negated = body.startswith("\\+")
    if negated:
        body = body[2:].strip()
        if body.startswith("(") and body.endswith(")"):  # \+ (Goal, Conjuncts)
            body = body[1:-1].strip()
    match = re.match(r"([a-z][A-Za-z0-9_]*)\(", body)
    if not match:
        raise ValueError("unparsed goal: " + goal)
    depth, quote = 0, None
    for i in range(match.end() - 1, len(body)):
        ch = body[i]
        if quote:
            if ch == quote and body[i - 1] != "\\":
                quote = None
        elif ch in "'\"":
            quote = ch
        elif ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
            if depth == 0:
                inner = body[match.end():i]
                return negated, match.group(1), split_args(inner), body[i + 1:].strip()
    raise ValueError("unbalanced goal: " + goal)


def mode_of(args):
    return "".join("f" if re.fullmatch(r"[A-Z_][A-Za-z0-9_]*", a) else "b" for a in args)


def h65_table():
    text = (ROOT / "human/DECISIONS.md").read_text()
    table = {}
    for line_no, line in enumerate(text.splitlines(), 1):
        row = re.match(r"\| (§[^|]+) \| `([a-z][A-Za-z0-9_]*)/(\d+)` \| ([^|]+) \| +(\d+) \| ([^|]*)\|", line)
        if row:
            modes = collections.Counter()
            for mode, count in re.findall(r"`([bf]+)`×(\d+)", row.group(4)):
                modes[mode] += int(count)
            table[(row.group(2), int(row.group(3)))] = {
                "section": row.group(1).strip(), "modes": modes, "cases": int(row.group(5)),
                "extra": row.group(6).strip(), "line": line_no}
    return table


def main():
    table = h65_table()
    roles = {(r["predicate"], r["arity"]): r["roles"]
             for r in json.loads((ROOT / "Interface/TIME_SCHEMA.json").read_text())["signatures"]}
    by_sig = collections.defaultdict(list)
    for path in sorted((ROOT / "human/sara/sara/cases").glob("*.pl")):
        text = path.read_text()
        question = " ".join(line.lstrip("% ").strip() for line in
                            text.split("% Question", 1)[1].split("% Facts", 1)[0].strip().splitlines())
        test = text.split("% Test", 1)[1]
        goal = test.split(":- halt.", 1)[0].strip()
        assert goal.startswith(":-") and goal.endswith("."), path.name
        negated, pred, args, rest = first_call(goal[2:-1])
        by_sig[(pred, len(args))].append({
            "case": path.name, "negated": negated, "mode": mode_of(args), "args": args,
            "rest": rest.lstrip(",").strip(), "question": question})
    problems = []
    for key, info in sorted(table.items()):
        seen = collections.Counter(c["mode"] for c in by_sig.get(key, []))
        if seen != info["modes"]:
            problems.append(f"{key[0]}/{key[1]}: parsed {dict(seen)} vs H6.5 {dict(info['modes'])}")
    extra = sorted(set(by_sig) - set(table))
    if extra:
        problems.append("signatures not in H6.5: " + ", ".join(f"{p}/{a}" for p, a in extra))
    lines = [
        "# Q-024 evidence: case goals, modes and questions",
        "",
        "Generated by `extract.py` in this directory from `human/sara/sara/cases/*.pl`,",
        "the H6.5 table in `human/DECISIONS.md` and `Interface/TIME_SCHEMA.json`, all",
        "read only. It records what each case binds and what its `% Question` says.",
        "It decides no output position: that is the question Q-024 asks.",
        "",
        f"Cases: {sum(len(v) for v in by_sig.values())}. Signatures: {len(by_sig)}. "
        f"H6.5 rows: {len(table)}. Mode check against H6.5: "
        + ("all parsed modes match." if not problems else "MISMATCHES below."),
        "",
    ]
    for problem in problems:
        lines.append(f"- MISMATCH: {problem}")
    if problems:
        lines.append("")
    lines += ["Columns: case; `¬` marks a `\\+` goal; the mode; the goal's arguments in",
              "order (`·` separated); any further conjuncts; the question text verbatim.", ""]
    for key in sorted(by_sig, key=lambda k: (table.get(k, {}).get("line", 10**6), k)):
        info = table.get(key, {})
        role = roles.get(key)
        lines.append(f"## `{key[0]}/{key[1]}`")
        lines.append("")
        lines.append(f"H6.5 ({info.get('section', '?')}, DECISIONS.md:{info.get('line', '?')}): "
                     + ", ".join(f"`{m}`×{n}" for m, n in sorted(info.get("modes", {}).items()))
                     + (f"; extra conjuncts: {info['extra']}" if info.get("extra") else "")
                     + (f". Time roles: {', '.join(role)}." if role else "."))
        lines.append("")
        lines.append("| Case | Mode | Arguments | Further conjuncts | Question |")
        lines.append("| --- | --- | --- | --- | --- |")
        for c in by_sig[key]:
            cell = lambda s: s.replace("|", "\\|").replace("\n", " ")
            lines.append(f"| `{c['case']}` | {'¬' if c['negated'] else ''}`{c['mode']}` | "
                         f"`{cell(' · '.join(c['args']))}` | {('`' + cell(' '.join(c['rest'].split())) + '`') if c['rest'] else ''} | "
                         f"{cell(c['question'])} |")
        lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: {sum(len(v) for v in by_sig.values())} cases, "
          f"{len(by_sig)} signatures, {len(problems)} mismatch(es)")
    for problem in problems:
        print("MISMATCH", problem)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
