payment_(alice_is_paid).
patient_(alice_is_paid,alice).
start_(alice_is_paid,"2016-12-31").
amount_(alice_is_paid,51020).
marriage_(alice_and_bob).
agent_(alice_and_bob,alice).
agent_(alice_and_bob,bob).
start_(alice_and_bob,"2016-02-03").
joint_return_(alice_and_bob_file_a_joint_return).
agent_(alice_and_bob_file_a_joint_return,alice).
agent_(alice_and_bob_file_a_joint_return,bob).
start_(alice_and_bob_file_a_joint_return,"2016-01-01").
end_(alice_and_bob_file_a_joint_return,"2016-12-31").
income_(bob_income).
agent_(bob_income,bob).
amount_(bob_income,42939).
start_(bob_income,"2016-12-31").
deduction_(itemized_deduction).
agent_(itemized_deduction,alice).
amount_(itemized_deduction,21137).
start_(itemized_deduction,"2016-12-31").
