payment_('alice_is_paid').
patient_('alice_is_paid','alice').
start_('alice_is_paid',"2017-12-31").
amount_('alice_is_paid',33200).
payment_('bob_is_paid').
patient_('bob_is_paid','bob').
start_('bob_is_paid',"2017-12-31").
amount_('bob_is_paid',10).
marriage_('alice_and_bob').
agent_('alice_and_bob','alice').
agent_('alice_and_bob','bob').
start_('alice_and_bob',"2017-02-03").
