brother_(alice_and_bob).
agent_(alice_and_bob,bob).
patient_(alice_and_bob,alice).
start_(alice_and_bob,"2014-01-31").
son_(bob_is_son).
agent_(bob_is_son,bob).
patient_(bob_is_son,bob_parents).
start_(bob_is_son,"2014-01-31").
residence_(bob_parents_residence).
agent_(bob_parents_residence,bob_parents).
patient_(bob_parents_residence,bob_parents_house).
residence_(bob_residence).
agent_(bob_residence,bob).
patient_(bob_residence,bob_parents_house).
start_(bob_residence,"2014-01-31").
income_(alice_income).
agent_(alice_income,alice).
start_(alice_income,"2016-12-31").
amount_(alice_income,567192).
marriage_(alice_marriage).
agent_(alice_marriage,alice).
agent_(alice_marriage,husband).
start_(alice_marriage,"2016-01-12").
deduction_(itemized_deduction).
agent_(itemized_deduction,alice).
amount_(itemized_deduction,100206).
start_(itemized_deduction,"2016-01-01").
