service_(alice_employed).
patient_(alice_employed,hospital).
agent_(alice_employed,alice).
start_(alice_employed,"2017-01-01").
end_(alice_employed,"2017-12-31").
payment_(alice_is_paid).
agent_(alice_is_paid,hospital).
patient_(alice_is_paid,alice).
start_(alice_is_paid,"2017-12-31").
purpose_(alice_is_paid,alice_employed).
amount_(alice_is_paid,200).
medical_institution_(hospital_is_a_medical_institution).
agent_(hospital_is_a_medical_institution,hospital).
incarceration_(alice_goes_to_hospital).
agent_(alice_goes_to_hospital,alice).
patient_(alice_goes_to_hospital,hospital).
start_(alice_goes_to_hospital,"2015-01-24").
end_(alice_goes_to_hospital,"2019-05-05").
