payment_('alice_is_paid').
patient_('alice_is_paid','alice').
start_('alice_is_paid',"2017-12-31").
amount_('alice_is_paid',33200).
marriage_('alice_and_bob').
agent_('alice_and_bob','alice').
agent_('alice_and_bob','bob').
start_('alice_and_bob',"2017-02-03").
blindness_('alice_is_blind').
agent_('alice_is_blind','alice').
start_('alice_is_blind',"2015-04-19").
