service_('alice_employer').
patient_('alice_employer','alice').
agent_('alice_employer','bob').
start_('alice_employer',"2005-02-01").
end_('alice_employer',"2005-09-02").
payment_('alice_pays').
agent_('alice_pays','alice').
patient_('alice_pays','bob').
start_('alice_pays',"2005-09-02").
purpose_('alice_pays','alice_employer').
amount_('alice_pays',4512).
payment_('alice_is_paid').
patient_('alice_is_paid','alice').
start_('alice_is_paid',"2005-12-31").
amount_('alice_is_paid',133200).
deduction_('itemized_deduction_1').
agent_('itemized_deduction_1','alice').
amount_('itemized_deduction_1',2939).
start_('itemized_deduction_1',"2005-01-01").
deduction_('itemized_deduction_2').
agent_('itemized_deduction_2','alice').
amount_('itemized_deduction_2',8744).
start_('itemized_deduction_2',"2005-01-01").
