payment_('alice_is_paid').
patient_('alice_is_paid','alice').
start_('alice_is_paid',"2019-12-31").
amount_('alice_is_paid',34510).
brother_('charlie_brother').
agent_('charlie_brother','charlie').
patient_('charlie_brother','alice').
son_('bob_is_son').
agent_('bob_is_son','bob').
patient_('bob_is_son','charlie').
residence_('bob_residence').
agent_('bob_residence','bob').
patient_('bob_residence','alice_house').
start_('bob_residence',"2019-01-01").
end_('bob_residence',"2019-12-31").
residence_('alice_residence').
agent_('alice_residence','alice').
patient_('alice_residence','alice_house').
start_('alice_residence',"2019-01-01").
end_('alice_residence',"2019-12-31").
payment_('alice_maintains_house').
agent_('alice_maintains_house','alice').
amount_('alice_maintains_house',1).
start_('alice_maintains_house',"2019-01-01").
purpose_('alice_maintains_house','alice_house').
residence_('charlie_residence').
agent_('charlie_residence','charlie').
patient_('charlie_residence','charlie_house').
start_('charlie_residence',"2019-01-01").
end_('charlie_residence',"2019-12-31").
