payment_(alice_is_paid).
patient_(alice_is_paid,alice).
start_(alice_is_paid,"2017-12-31").
amount_(alice_is_paid,33200).
marriage_(alice_and_bob).
agent_(alice_and_bob,alice).
agent_(alice_and_bob,bob).
start_(alice_and_bob,"2017-02-03").
joint_return_(bob_and_alice_joint_return).
agent_(bob_and_alice_joint_return,bob).
agent_(bob_and_alice_joint_return,alice).
start_(bob_and_alice_joint_return,"2017-01-01").
end_(bob_and_alice_joint_return,"2017-12-31").
