service_('alice_employed').
patient_('alice_employed','jail').
agent_('alice_employed','alice').
start_('alice_employed',"2017-01-01").
end_('alice_employed',"2017-12-31").
payment_('alice_is_paid').
agent_('alice_is_paid','jail').
patient_('alice_is_paid','alice').
start_('alice_is_paid',"2017-12-31").
purpose_('alice_is_paid','alice_employed').
amount_('alice_is_paid',200).
penal_institution_('jail_is_a_penal_institution').
agent_('jail_is_a_penal_institution','jail').
incarceration_('alice_goes_to_jail').
agent_('alice_goes_to_jail','alice').
patient_('alice_goes_to_jail','jail').
start_('alice_goes_to_jail',"2015-01-24").
end_('alice_goes_to_jail',"2019-05-05").
