income_(alice_income_2010).
agent_(alice_income_2010,alice).
amount_(alice_income_2010,210204).
start_(alice_income_2010,"2010-12-31").
service_(alice_employer).
patient_(alice_employer,alice).
agent_(alice_employer,bob).
start_(alice_employer,"2010-01-01").
end_(alice_employer,"2010-12-31").
payment_(alice_pays_bob).
agent_(alice_pays_bob,alice).
patient_(alice_pays_bob,bob).
start_(alice_pays_bob,"2010-01-01").
end_(alice_pays_bob,"2010-12-31").
purpose_(alice_pays_bob,alice_employer).
amount_(alice_pays_bob,45252).
payment_(alice_pays_retirement).
agent_(alice_pays_retirement,alice).
patient_(alice_pays_retirement,retirement_fund).
purpose_(alice_pays_retirement,"make provisions for employees in case of retirement").
plan_(retirement_fund).
beneficiary_(alice_pays_retirement,bob).
start_(alice_pays_retirement,"2010-01-01").
end_(alice_pays_retirement,"2010-12-31").
amount_(alice_pays_retirement,9832).
payment_(alice_pays_insurance).
agent_(alice_pays_insurance,alice).
patient_(alice_pays_insurance,health_insurance_fund).
plan_(health_insurance_fund).
purpose_(alice_pays_insurance,"make provisions in case of sickness").
beneficiary_(alice_pays_insurance,charlie).
start_(alice_pays_insurance,"2010-01-01").
end_(alice_pays_insurance,"2010-12-31").
amount_(alice_pays_insurance,5322).
father_(alice_and_charlie).
agent_(alice_and_charlie,charlie).
patient_(alice_and_charlie,alice).
retirement_(charlie_retires).
agent_(charlie_retires,charlie).
start_(charlie_retires,"2009-01-01").
