income_('alice_is_paid').
agent_('alice_is_paid','alice').
start_('alice_is_paid',"2017-12-31").
amount_('alice_is_paid',33200).
marriage_('alice_and_bob').
agent_('alice_and_bob','alice').
agent_('alice_and_bob','bob').
start_('alice_and_bob',"2017-02-03").
blindness_('alice_is_blind').
agent_('alice_is_blind','alice').
start_('alice_is_blind',"2013-10-04").
joint_return_('alice_and_bob_joint_return').
agent_('alice_and_bob_joint_return','alice').
agent_('alice_and_bob_joint_return','bob').
start_('alice_and_bob_joint_return',"2017-01-01").
end_('alice_and_bob_joint_return',"2017-12-31").
residence_('alice_residence').
agent_('alice_residence','alice').
patient_('alice_residence','home').
start_('alice_residence',"2017-01-01").
end_('alice_residence',"2020-12-31").
residence_('bob_residence').
agent_('bob_residence','bob').
patient_('bob_residence','home').
start_('bob_residence',"2017-01-01").
end_('bob_residence',"2020-12-31").
