marriage_(alice_and_bob).
agent_(alice_and_bob,alice).
agent_(alice_and_bob,bob).
start_(alice_and_bob,"1992-02-03").
death_(alice_dies).
agent_(alice_dies,alice).
start_(alice_dies,"2014-07-09").
end_(alice_dies,"2014-07-09").
marriage_(bob_and_charlie).
agent_(bob_and_charlie,charlie).
agent_(bob_and_charlie,bob).
start_(bob_and_charlie,"2015-09-14").
