marriage_('alice_and_bob').
agent_('alice_and_bob','alice').
agent_('alice_and_bob','bob').
start_('alice_and_bob',"2015-01-01").
joint_return_('alice_and_bob_joint_return').
agent_('alice_and_bob_joint_return','alice').
agent_('alice_and_bob_joint_return','bob').
start_('alice_and_bob_joint_return',"2015-01-01").
end_('alice_and_bob_joint_return',"2015-12-31").
